name: build-deploy-assets

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make all
      - name: Delete old release asset
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          fail-if-no-assets: false
          tag: latest
          assets: lkmpg.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: lkmpg.pdf
          tag_name: "latest"
          prerelease: true
